// frontend/src/domains/auth/components/LoginForm.tsx
import type { FormEvent } from 'react'
import { useState } from 'react'

import { Button } from '@/shared/components/Button'
import { ErrorState } from '@/shared/components/ErrorState'
import { LoadingState } from '@/shared/components/LoadingState'
import { useAuth } from '@/domains/auth/hooks/useAuth'

type LoginFormProps = {
  onSuccess?: () => void
}

export function LoginForm({ onSuccess }: LoginFormProps) {
  const { error, isLoading, login } = useAuth()
  const [credential, setCredential] = useState('')
  const [password, setPassword] = useState('')

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    await login({ credential, password })
    onSuccess?.()
  }

  return (
    <form onSubmit={handleSubmit}>
      <div className="field">
        <label htmlFor="auth-credential">Email or username</label>
        <input
          id="auth-credential"
          name="credential"
          type="text"
          value={credential}
          autoComplete="username"
          placeholder="student@example.com or student-user"
          required
          onChange={(event) => setCredential(event.target.value)}
        />
      </div>

      <div className="field">
        <label htmlFor="auth-password">Password</label>
        <input
          id="auth-password"
          name="password"
          type="password"
          value={password}
          autoComplete="current-password"
          required
          onChange={(event) => setPassword(event.target.value)}
        />
      </div>

      {error ? <ErrorState message={error} /> : null}
      {isLoading ? <LoadingState label="Signing in..." /> : null}

      <Button type="submit" disabled={isLoading}>
        {isLoading ? 'Logging in...' : 'Log in'}
      </Button>
    </form>
  )
}

// frontend/src/domains/auth/components/LoginForm.vue
<script setup lang="ts">
import { ref } from 'vue'

import { useAuth } from '@/domains/auth/hooks/useAuth'
import Button from '@/shared/components/Button.vue'
import ErrorState from '@/shared/components/ErrorState.vue'
import LoadingState from '@/shared/components/LoadingState.vue'

const emit = defineEmits<{
  (event: 'success'): void
}>()

const { error, isLoading, login } = useAuth()
const credential = ref('')
const password = ref('')

async function handleSubmit() {
  await login({ credential: credential.value, password: password.value })
  emit('success')
}
</script>

<template>
  <form @submit.prevent="handleSubmit">
    <div class="field">
      <label for="auth-credential">Email or username</label>
      <input
        id="auth-credential"
        v-model="credential"
        name="credential"
        type="text"
        autocomplete="username"
        placeholder="student@example.com or student-user"
        required
      >
    </div>

    <div class="field">
      <label for="auth-password">Password</label>
      <input
        id="auth-password"
        v-model="password"
        name="password"
        type="password"
        autocomplete="current-password"
        required
      >
    </div>

    <ErrorState v-if="error" :message="error" />
    <LoadingState v-if="isLoading" label="Signing in..." />

    <Button type="submit" :disabled="isLoading">
      {{ isLoading ? 'Logging in...' : 'Log in' }}
    </Button>
  </form>
</template>
