// frontend/src/pages/HomeRedirectPage.tsx
import { useSyncExternalStore } from 'react'
import { Navigate } from 'react-router-dom'

import { authStore } from '@/domains/auth/store/authStore'

export function HomeRedirectPage() {
  const { token } = useSyncExternalStore(authStore.subscribe, authStore.getState, authStore.getInitialState)

  return <Navigate replace to={token ? '/dashboard' : '/login'} />
}

// frontend/src/pages/HomeRedirectPage.vue
<script setup lang="ts">
import { onMounted } from 'vue'
import { useRouter } from 'vue-router'

import { authStore } from '@/domains/auth/store/authStore'

const router = useRouter()

onMounted(() => {
  router.replace(authStore.getState().token ? '/dashboard' : '/login')
})
</script>

<template>
  <main class="page-shell">
    <p class="section-lede">Redirecting...</p>
  </main>
</template>
