// frontend/src/pages/NotFoundPage.vue
<template>
  <main class="page-shell">
    <Card>
      <section class="section-stack" aria-labelledby="not-found-title">
        <h1 id="not-found-title">Page not found</h1>
        <p class="section-lede">The route you opened does not exist in this app.</p>
        <p>
          <RouterLink to="/">Go back to the app home</RouterLink>
        </p>
      </section>
    </Card>
  </main>
</template>

<script setup lang="ts">
import { RouterLink } from 'vue-router'

import Card from '@/shared/components/Card.vue'
</script>

// frontend/src/pages/NotFoundPage.tsx
import { Link } from 'react-router-dom'

import { Card } from '@/shared/components/Card'

export function NotFoundPage() {
  return (
    <main className="page-shell">
      <Card>
        <section className="section-stack" aria-labelledby="not-found-title">
          <h1 id="not-found-title">Page not found</h1>
          <p className="section-lede">The route you opened does not exist in this app.</p>
          <p>
            <Link to="/">Go back to the app home</Link>
          </p>
        </section>
      </Card>
    </main>
  )
}
