// frontend/src/domains/auth/pageSection/LoginSection.vue
<template>
  <Card>
    <section class="section-stack" aria-labelledby="login-title">
      <h1 id="login-title">Log in to start your codebase understanding exam.</h1>
      <p class="section-lede">
        This platform verifies real codebase understanding before students begin their exam.
      </p>
      <LoginForm @success="$emit('loginSuccess')" />
    </section>
  </Card>
</template>

<script setup lang="ts">
import LoginForm from '@/domains/auth/components/LoginForm.vue'
import Card from '@/shared/components/Card.vue'

defineEmits<{
  (event: 'loginSuccess'): void
}>()
</script>

// frontend/src/domains/auth/pageSection/LoginSection.tsx
import { LoginForm } from '@/domains/auth/components/LoginForm'
import { Card } from '@/shared/components/Card'

type LoginSectionProps = {
  onLoginSuccess?: () => void
}

export function LoginSection({ onLoginSuccess }: LoginSectionProps) {
  return (
    <Card>
      <section className="section-stack" aria-labelledby="login-title">
        <h1 id="login-title">Log in to start your codebase understanding exam.</h1>
        <p className="section-lede">This platform verifies real codebase understanding before students begin their exam.</p>
        <LoginForm onSuccess={onLoginSuccess} />
      </section>
    </Card>
  )
}
